"""add scan runner lifecycle fields

Revision ID: 41e1232a517d
Revises: 8fe56d3d3a2f
Create Date: 2026-08-12 13:57:07.728452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e1232a517d'
down_revision: Union[str, None] = '8fe56d3d3a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_requests', sa.Column('runner_machine_id', sa.String(length=64), nullable=True))
    op.add_column('scan_requests', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scan_requests', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_requests', 'retry_count')
    op.drop_column('scan_requests', 'heartbeat_at')
    op.drop_column('scan_requests', 'runner_machine_id')
    # ### end Alembic commands ###
