"""initial schema

Revision ID: 8fe56d3d3a2f
Revises: 
Create Date: 2026-08-11 22:33:47.326371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe56d3d3a2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_rules',
    sa.Column('rule_key', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('default_severity', sa.String(length=16), nullable=False),
    sa.Column('default_confidence', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key', 'version', name='uq_finding_rules_key_version')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('scan_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('normalized_domain', sa.String(length=255), nullable=False),
    sa.Column('original_input', sa.String(length=2048), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('authorization_confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_requests_normalized_domain'), 'scan_requests', ['normalized_domain'], unique=False)
    op.create_index(op.f('ix_scan_requests_status'), 'scan_requests', ['status'], unique=False)
    op.create_table('dns_observations',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('lookup_successful', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('spf_record', sa.Text(), nullable=True),
    sa.Column('dmarc_record', sa.Text(), nullable=True),
    sa.Column('dmarc_policy', sa.String(length=32), nullable=True),
    sa.Column('dmarc_pct', sa.String(length=16), nullable=True),
    sa.Column('dmarc_rua', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_observations_scan_request_id'), 'dns_observations', ['scan_request_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_url_or_identifier', sa.String(length=2048), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('normalized_payload_json', sa.JSON(), nullable=False),
    sa.Column('human_readable_summary', sa.Text(), nullable=False),
    sa.Column('raw_response_reference', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_scan_request_id'), 'evidence_items', ['scan_request_id'], unique=False)
    op.create_table('findings',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('recommended_next_step', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['finding_rules.id'], ),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_scan_request_id'), 'findings', ['scan_request_id'], unique=False)
    op.create_table('http_observations',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('redirect_chain', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('cache_control', sa.String(length=255), nullable=True),
    sa.Column('server_header', sa.String(length=255), nullable=True),
    sa.Column('strict_transport_security', sa.String(length=255), nullable=True),
    sa.Column('content_security_policy', sa.Text(), nullable=True),
    sa.Column('x_content_type_options', sa.String(length=255), nullable=True),
    sa.Column('x_frame_options', sa.String(length=255), nullable=True),
    sa.Column('referrer_policy', sa.String(length=255), nullable=True),
    sa.Column('permissions_policy', sa.Text(), nullable=True),
    sa.Column('response_duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_https', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_observations_scan_request_id'), 'http_observations', ['scan_request_id'], unique=False)
    op.create_table('pages',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('robots_directives', sa.String(length=255), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=False),
    sa.Column('first_h1', sa.String(length=1024), nullable=True),
    sa.Column('html_lang', sa.String(length=32), nullable=True),
    sa.Column('meta_viewport_present', sa.Boolean(), nullable=False),
    sa.Column('structured_data_types', sa.JSON(), nullable=False),
    sa.Column('internal_link_count', sa.Integer(), nullable=False),
    sa.Column('external_link_count', sa.Integer(), nullable=False),
    sa.Column('response_duration_ms', sa.Integer(), nullable=True),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_scan_request_id'), 'pages', ['scan_request_id'], unique=False)
    op.create_table('performance_observations',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('response_duration_ms', sa.Integer(), nullable=True),
    sa.Column('html_bytes', sa.Integer(), nullable=True),
    sa.Column('third_party_domain_count', sa.Integer(), nullable=True),
    sa.Column('js_resource_count', sa.Integer(), nullable=True),
    sa.Column('lcp_ms', sa.Float(), nullable=True),
    sa.Column('cls', sa.Float(), nullable=True),
    sa.Column('inp_ms', sa.Float(), nullable=True),
    sa.Column('fcp_ms', sa.Float(), nullable=True),
    sa.Column('ttfb_ms', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('best_practices_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_observations_scan_request_id'), 'performance_observations', ['scan_request_id'], unique=False)
    op.create_table('reports',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('storage_path', sa.String(length=2048), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_scan_request_id'), 'reports', ['scan_request_id'], unique=False)
    op.create_table('scan_events',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_jobs',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_targets',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('resolved_ips', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_request_id')
    )
    op.create_table('third_party_dependencies',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('classification_method', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_third_party_dependencies_scan_request_id'), 'third_party_dependencies', ['scan_request_id'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_item_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'evidence_item_id', name='uq_finding_evidence')
    )
    op.create_index(op.f('ix_finding_evidence_evidence_item_id'), 'finding_evidence', ['evidence_item_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_finding_id'), 'finding_evidence', ['finding_id'], unique=False)
    op.create_table('technology_observations',
    sa.Column('scan_request_id', sa.Uuid(), nullable=False),
    sa.Column('technology_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('detection_method', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence_item_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_request_id'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_observations_scan_request_id'), 'technology_observations', ['scan_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technology_observations_scan_request_id'), table_name='technology_observations')
    op.drop_table('technology_observations')
    op.drop_index(op.f('ix_finding_evidence_finding_id'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_evidence_item_id'), table_name='finding_evidence')
    op.drop_table('finding_evidence')
    op.drop_index(op.f('ix_third_party_dependencies_scan_request_id'), table_name='third_party_dependencies')
    op.drop_table('third_party_dependencies')
    op.drop_table('scan_targets')
    op.drop_table('scan_jobs')
    op.drop_table('scan_events')
    op.drop_index(op.f('ix_reports_scan_request_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_performance_observations_scan_request_id'), table_name='performance_observations')
    op.drop_table('performance_observations')
    op.drop_index(op.f('ix_pages_scan_request_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_http_observations_scan_request_id'), table_name='http_observations')
    op.drop_table('http_observations')
    op.drop_index(op.f('ix_findings_scan_request_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_evidence_items_scan_request_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_dns_observations_scan_request_id'), table_name='dns_observations')
    op.drop_table('dns_observations')
    op.drop_index(op.f('ix_scan_requests_status'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_normalized_domain'), table_name='scan_requests')
    op.drop_table('scan_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('finding_rules')
    # ### end Alembic commands ###
